global:
  scrape_interval: 3s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    scheme: "http"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "prometheus:9090"

  - job_name: "kyuubi"
    scheme: "http"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "hadoop-master1.orb.local:10019"

  - job_name: "zookeeper"
    scheme: "http"
    metrics_path: "/metrics"
    static_configs:
      - targets:
          - "hadoop-master1.orb.local:7000"
